# model-definition.yml

kind: Model
apiVersion: v1alpha4

metadata:
  displayName: HiPIMS
  name: hipims-flood-model
  summary: Hydrodynamic flood model (HiPIMS) for high resolution flood modelling
  description: >
    HiPIMS allows for high resolution flood modelling using GPU processing methods to execute the modelling in quick
    execution times.
  type: model

spec:
  resources:
    useGPU: True
  inputs:
    env:
      - name: ForecastID
        title: Forecast ID
        desc: Rainfall forecast ID
        type: integer
        default: 1
        min: 1
        max: 11

  dataslots:
    - name: DEM
      description: The DEM covering the area of interest
      path: dem/
      required: true
      default:
        - 383dfcba-c0d3-4e3c-aaba-48f456f5d2eb
        -
  outputs:
    datasets:
      - name: flood outputs
        desc: Set of files describing the floodig at time steps through the analysis

