name: Upload to DAFNI

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t hipims .

      - name: Compress docker image
        run: docker save hipims | gzip > hipims.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.9
        with:
          definition-path: './model-definition.yml'
          image-path: './hipims.tar.gz'
          username: ${{ secrets.DAFNI_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: "218094e2-f9a8-445d-bbaf-30dcc1efac42 "
